name: PRs to master
on: 
  pull_request:
    branches: production
    types: closed
jobs:
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge production back to staging
      run: |
          git fetch --unshallow
          git checkout staging
          git pull
          git merge --no-ff production -m "Auto-merge production back to staging"
          git push
    - name: Merge staging back to devel
      run: |
          git fetch --unshallow
          git checkout devel
          git pull
          git merge --no-ff staging -m "Auto-merge staging back to devel"
          git push
